name: 'Manual Deploy'

on:
  workflow_dispatch:
      
jobs:
  deploy:
    uses: ./.github/workflows/workspace-deploy.yml
    with:
      ENVIRONMENT: ${{ github.actor }}-${{ github.ref_name }}
      REPO_REF: ${{ github.ref_name }}
      TF_MODULES_REF: ${{ github.ref_name }}
      ANSIBLE_MODULES_REF: ${{ github.ref_name }}
      FLUX_WORKSPACE: ${{ github.ref_name }}
      TERRAFORM_APPLY: true
      ANSIBLE_APPLY: true
    secrets: inherit