name: 'Github Cleanup'

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: MajorScruffy/delete-old-workflow-runs@v0.3.0
        with:
          repository: tomp736/pymp_infra
          older-than-seconds: 21600
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_WF_RW }}