name: 'Github Cleanup'

on:
  workflow_dispatch:
  schedule:
    - cron:  '*/10 * * * *'

jobs:
  delete-slow:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: MajorScruffy/delete-old-workflow-runs@v0.3.0
        with:
          repository: tomp736/pymp_infra
          older-than-seconds: 3600
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_WF_RW }}
  delete-fast:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workflow: 
          - workspace-cleanup
          - github-cleanup
    steps:
      - name: Delete workflow runs
        uses: MajorScruffy/delete-old-workflow-runs@v0.3.0
        with:
          repository: tomp736/pymp_infra
          older-than-seconds: 60
          workflow: .github/workflows/${{ matrix.workflow }}.yml
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_WF_RW }}