name: 'Manual Destroy'

on:
  workflow_dispatch:
      
jobs:
  destroy:
    uses: ./.github/workflows/workspace-destroy.yml
    with:
      ENVIRONMENT: ${{ github.actor }}-${{ github.ref_name }}
      TF_MODULES_REF: ${{ github.ref_name }}
    secrets: inherit